-- MySQL Script generated by MySQL Workbench
-- Wed Feb 17 14:52:14 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pokes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pokes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pokes` DEFAULT CHARACTER SET utf8 ;
USE `pokes` ;

-- -----------------------------------------------------
-- Table `pokes`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokes`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `alias` VARCHAR(45) NULL DEFAULT NULL,
  `dob` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pokes`.`poked_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokes`.`poked_users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `poked_user_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_poked_users_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_poked_users_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `pokes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pokes`.`pokes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokes`.`pokes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `counter` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `pokee_id` INT(11) NOT NULL,
  `poker_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pokes_users_idx` (`pokee_id` ASC),
  INDEX `fk_pokes_users1_idx` (`poker_id` ASC),
  CONSTRAINT `fk_pokes_users`
    FOREIGN KEY (`pokee_id`)
    REFERENCES `pokes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokes_users1`
    FOREIGN KEY (`poker_id`)
    REFERENCES `pokes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
